apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy
    version: 1.6.3
    namespace: infrastructure-gatewayapi
    includeCRDs: false
    valuesFile: values.yaml
namespace: infrastructure-gatewayapi

# there is no kustomize base intentionally.
# i'm installing envoy gateway once using
# namespace mode.
# i'm leaving this folder structure so that
# i can potentially use argocd application sets
# in the future.
