apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - resources/routeArgocd.yaml
patches: # using strategic merge patches here
  - patches/argocdCm.yaml
  - patches/argocdCmdParamsCm.yaml

# there is no kustomize base intentionally.
# argocd should only be installed once.
# i'm leaving this folder structure so that
# i can potentially use argocd application sets
# in the future.
