apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure
helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy/
    version: 1.7.0
    includeCRDs: false
    valuesFile: values.yaml
    namespace: infrastructure
resources:
  - resources/envoyProxy.yaml
