apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/
  - resources/gatewayClass.yaml
  - resources/routeArgocd.yaml
  - resources/routeCiliumHubble.yaml
  - resources/routeLonghorn.yaml
patches:
  - path: patches/gateway.yaml
    target:
      kind: Gateway
      name: huntinternal
  - path: patches/gatewayTlsTerminationCertificate.yaml
    target:
      kind: Certificate
      name: gateway-huntinternal-tls-termination
  - path: patches/envoyProxy.yaml
    target:
      kind: EnvoyProxy
      name: huntinternal
  - path: patches/routeHttpToHttpsRedirect.yaml
    target:
      kind: HTTPRoute
      name: http-to-https-redirect
