apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts/
    version: 1.19.2
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.yaml
resources:
  - resources/namespace.yaml
  - resources/selfsignedIssuer.yaml
  - resources/selfsignedRootCaCertificate.yaml
  - resources/huntInternalClusterIssuer.yaml

# there is no kustomize base intentionally.
# cert-manager should only be installed once.
# i'm leaving this folder structure so that
# i can potentially use argocd application sets
# in the future.
