apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.18.6
    namespace: kube-system
    includeCRDs: true
    valuesFile: values.yaml
resources:
  - resources/loadBalancerIpAddressManagement.yaml
  - resources/layer2Announcements.yaml
  - resources/routeCiliumHubble.yaml

# there is no kustomize base intentionally.
# cilium should only be installed once.
# i'm leaving this folder structure so that
# i can potentially use argocd application sets
# in the future.
