apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io/
    version: 1.10.1
    namespace: longhorn-system
    includeCRDs: true
    valuesFile: values.yaml
resources:
  - resources/namespace.yaml
  - resources/routeLonghorn.yaml

# there is no kustomize base intentionally.
# longhorn should only be installed once.
# i'm leaving this folder structure so that
# i can potentially use argocd application sets
# in the future.
