apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager
helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts/
    version: 1.19.2
    namespace: cert-manager
    releaseName: cert-manager
    includeCRDs: true
    valuesFile: values.yaml
