apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.19.2/cert-manager.yaml
  - resources/selfsignedIssuer.yaml
  - resources/selfsignedRootCaCertificate.yaml
  - resources/huntInternalClusterIssuer.yaml
  - resources/huntInternalDevelopmentHomeTlsTerminationCertificate.yaml
  - resources/huntInternalDevelopmentLabTlsTerminationCertificate.yaml
  - resources/huntInternalProductionHomeTlsTerminationCertificate.yaml
  - resources/huntInternalProductionLabTlsTerminationCertificate.yaml
