apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/envoyProxy.yaml
  - resources/gatewayTlsTerminationCertificate.yaml
  - resources/gateway.yaml
  - resources/routeHttpToHttpsRedirect.yaml
