apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/gatewayTlsTerminationCertificate.yaml
  - resources/gatewayClass.yaml
  - resources/gateway.yaml
  - resources/routeArgocd.yaml
  - resources/routeLonghorn.yaml
  - resources/routeHttpToHttpsRedirect.yaml
